name: "Build"
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: ['**']
jobs:
  build:
    strategy:
      matrix:
          os: [ubuntu-20.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
    - uses: cachix/cachix-action@v10
      with:
        # TODO: your cache name
        name: example
        # TODO: set cachix token in github secrets
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check --print-build-logs
